# SPDX-License-Identifier: Apache-2.0

CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_BOOTLOADER_MCUBOOT=y

# Flash and Image Manager for MCUboot slot confirmation
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_STREAM_FLASH=y
CONFIG_IMG_MANAGER=y
CONFIG_MCUBOOT_IMG_MANAGER=y

# Console via USB-Serial/JTAG
CONFIG_SERIAL=y
CONFIG_UART_CONSOLE=y
CONFIG_UART_LINE_CTRL=y

# LED Strip driver (WS2812 over I2S)
CONFIG_LED_STRIP=y
CONFIG_WS2812_STRIP_I2S=y

# Watchdog
CONFIG_WATCHDOG=y
CONFIG_WDT_ESP32=y
CONFIG_WDT_LOG_LEVEL_INF=y
